//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorFinanceiro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class caixa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public caixa()
        {
            this.logcaixa = new HashSet<logcaixa>();
            this.venda = new HashSet<venda>();
        }
    
        public int id { get; set; }
        public decimal valorabertura { get; set; }
        public Nullable<decimal> valorfechamento { get; set; }
        public System.DateTime horaabertura { get; set; }
        public Nullable<System.DateTime> horafechamento { get; set; }
        public int lancamento_id { get; set; }
    
        public virtual lancamento lancamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<logcaixa> logcaixa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<venda> venda { get; set; }
    }
}
