//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorFinanceiro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contasaldo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contasaldo()
        {
            this.lancamento = new HashSet<lancamento>();
            this.lancamentoestoque = new HashSet<lancamentoestoque>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public string banco { get; set; }
        public decimal saldo { get; set; }
        public bool status { get; set; }
        public string agencia { get; set; }
        public string conta { get; set; }
        public string titular { get; set; }
        public string tipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lancamento> lancamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lancamentoestoque> lancamentoestoque { get; set; }
    }
}
