//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorFinanceiro.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class contasaldo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contasaldo()
        {
            this.lancamento = new HashSet<lancamento>();
        }
    
        public int id { get; set; }
        [Display(Name = "Apelido para a conta:")]
        public string nome { get; set; }
        [Display(Name = "Banco:")]
        public string banco { get; set; }
        [Display(Name = "Saldo inicial:")]
        public decimal saldo { get; set; }
        [Display(Name = "Status:")]
        public bool status { get; set; }
        [Display(Name = "Agência:")]
        public string agencia { get; set; }
        [Display(Name = "Conta:")]
        public string conta { get; set; }
        [Display(Name = "Titular:")]
        public string titular { get; set; }
        [Display(Name = "Tipo de conta:")]
        public string tipo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lancamento> lancamento { get; set; }
    }
}
