//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorFinanceiro.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinanceiroBanco : DbContext
    {
        public FinanceiroBanco()
            : base("name=FinanceiroBanco")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<lancamento> lancamento { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<categoriadespesa> categoriadespesa { get; set; }
        public virtual DbSet<categoriareceita> categoriareceita { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<fornecedor> fornecedor { get; set; }
    }
}
