//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorFinanceiro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lancamentoestoque
    {
        public long id { get; set; }
        public Nullable<System.DateTime> dataentrada { get; set; }
        public Nullable<System.DateTime> datasaida { get; set; }
        public Nullable<System.DateTime> validade { get; set; }
        public string lote { get; set; }
        public int produto_id { get; set; }
        public int contasaldo_id { get; set; }
        public int estoque_id { get; set; }
        public Nullable<int> usuario_id { get; set; }
        public decimal valor { get; set; }
        public int quantidade { get; set; }
    
        public virtual contasaldo contasaldo { get; set; }
        public virtual estoque estoque { get; set; }
        public virtual produto produto { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
