//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorFinanceiro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lancamento
    {
        public int id { get; set; }
        public string descricao { get; set; }
        public Nullable<int> quantidade { get; set; }
        public decimal valor { get; set; }
        public bool pago { get; set; }
        public string numerotitulo { get; set; }
        public Nullable<System.DateTime> datavencimento { get; set; }
        public Nullable<System.DateTime> dataemissao { get; set; }
        public System.DateTime datacadastro { get; set; }
        public string observacao { get; set; }
        public int categoria_id { get; set; }
        public int instituicao_id { get; set; }
        public int contasaldo_id { get; set; }
        public Nullable<int> usuario_id { get; set; }
    
        public virtual contasaldo contasaldo { get; set; }
        public virtual instituicao instituicao { get; set; }
        public virtual categoria categoria { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
