//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorFinanceiro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lancamento
    {
        public int id { get; set; }
        public string descricao { get; set; }
        public string tipo { get; set; }
        public Nullable<int> quantidade { get; set; }
        public decimal valor { get; set; }
        public bool pago { get; set; }
        public string numerotitulo { get; set; }
        public Nullable<System.DateTime> datavencimento { get; set; }
        public string dataemissao { get; set; }
        public System.DateTime datacadastro { get; set; }
        public string observacao { get; set; }
        public int categoriareceita_id { get; set; }
        public int categoriadespesa_id { get; set; }
        public int cliente_id { get; set; }
        public int fornecedor_id { get; set; }
    
        public virtual categoriadespesa categoriadespesa { get; set; }
        public virtual categoriareceita categoriareceita { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual fornecedor fornecedor { get; set; }
    }
}
