//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorFinanceiro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class logcaixa
    {
        public int id { get; set; }
        public string tipo { get; set; }
        public decimal valor { get; set; }
        public System.DateTime horario { get; set; }
        public string motivo { get; set; }
        public string responsavel { get; set; }
        public int caixa_id { get; set; }
    
        public virtual caixa caixa { get; set; }
    }
}
