//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorFinanceiro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagamento
    {
        public int id { get; set; }
        public decimal valor { get; set; }
        public int parcelas { get; set; }
        public Nullable<System.DateTime> datainicio { get; set; }
        public int tipopagamento_id { get; set; }
        public int venda_id { get; set; }
    
        public virtual tipopagamento tipopagamento { get; set; }
        public virtual venda venda { get; set; }
    }
}
