//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorFinanceiro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produtovenda
    {
        public int id { get; set; }
        public int quantidade { get; set; }
        public decimal valor { get; set; }
        public Nullable<decimal> desconto { get; set; }
        public int venda_id { get; set; }
        public int produtoemestoque_produto_id { get; set; }
        public int produtoemestoque_estoque_id { get; set; }
    
        public virtual produtoemestoque produtoemestoque { get; set; }
        public virtual venda venda { get; set; }
    }
}
