//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorFinanceiro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produtolancamento
    {
        public int produto_id { get; set; }
        public int estoque_id { get; set; }
        public int lancamento_id { get; set; }
        public Nullable<System.DateTime> validade { get; set; }
        public string lote { get; set; }
        public Nullable<int> quantidade { get; set; }
        public Nullable<decimal> valor { get; set; }
    
        public virtual estoque estoque { get; set; }
        public virtual lancamento lancamento { get; set; }
        public virtual produto produto { get; set; }
    }
}
