//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorFinanceiro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produtoemestoque
    {
        public int produto_id { get; set; }
        public int estoque_id { get; set; }
        public int quantidade { get; set; }
    
        public virtual estoque estoque { get; set; }
        public virtual produto produto { get; set; }
    }
}
