//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciadorFinanceiro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class venda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public venda()
        {
            this.concluida = true;
            this.notafiscalvenda = new HashSet<notafiscalvenda>();
            this.pagamento = new HashSet<pagamento>();
            this.produtovenda = new HashSet<produtovenda>();
        }
    
        public int id { get; set; }
        public bool concluida { get; set; }
        public Nullable<decimal> valortotal { get; set; }
        public int caixa_id { get; set; }
        public int usuario_id { get; set; }
        public int instituicao_id { get; set; }
    
        public virtual instituicao instituicao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notafiscalvenda> notafiscalvenda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pagamento> pagamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<produtovenda> produtovenda { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual caixa caixa { get; set; }
    }
}
